name: Test Branch
on: [push]
jobs:
  test-branch:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: sudo apt update && sudo apt upgrade -y && sudo apt install make
      - name: Run Unit Tests
        run: make test